// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "SangtacApp",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "SangtacApp",
            targets: ["SangTacAppPlugin"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", from: "8.0.0")
    ],
    targets: [
        .target(
            name: "SangTacAppPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm")
            ],
            path: "ios/Sources/SangTacAppPlugin",
            // The site's own static boot assets, mirrored into the app so the
            // boot no longer pays a network round trip per file. Generated by
            // scripts/gen-site-assets.js; CI re-hashes them with `--check`.
            resources: [.copy("site-assets")])
    ]
)
