import Foundation

/**
 The app-side half of the site-asset mirror.

 Why this exists: the site's shell HTML ask for its own boot-critical bundles
 with a `Math.random()` cache-buster (`/asset/app.v2.js?0.3719...`), so WebKit can
 never serve them from its disk cache, and the remaining static files are
 requested by the HTML parser, where no injected hook can reach them. Both groups
 are exactly what the reader waits for before the app paints. The only way to take
 them off the network is to ship a copy inside the app and hand it to the page
 from the document-start shim (`assetMirror` in SitePatch.swift).

 What is stored:

   - `plugins/app/ios/Sources/SangTacAppPlugin/site-assets/` is the *baseline*
     snapshot, generated by `scripts/gen-site-assets.js` and copied into the app
     bundle by SwiftPM (see the target's `resources` in Package.swift). CI verifies
     the snapshot with `gen-site-assets.js --check` and verifies that the built app
     really contains it.
   - `Library/Application Support/stv-site-assets/` holds anything the site has
     since published differently. `assetMirror` revalidates each mirrored file
     once per launch with `If-Modified-Since`; a 200 response is stored here and
     wins over the snapshot from the next launch on. A stale snapshot therefore
     costs one launch at most.

 Two deliberate choices:

   - **No `Bundle.module`.** SwiftPM's generated accessor calls `fatalError` when
     the resource bundle is not where it expects, which would turn a packaging
     mistake into a launch crash on a device nobody here can debug. The lookup
     below returns nil instead, and a missing bundle only means the mirror never
     activates (the page then fetches everything from the network exactly as it
     did before this feature existed).
   - **JSONSerialization, not a Swift string literal.** The bundles are full of
     backslashes, both quote styles and Vietnamese non-ASCII; quoting them by hand
     is the same class of mistake that once shipped a syntactically dead shim
     (docs/capacitor-port.md 6.1). Letting Foundation do the escaping makes that
     impossible. It is also why this file contains no multiline string literal at
     all (scripts/check-ios-shim.js scans those for backslashes).
 */
enum SiteAssets {

    struct Asset {
        /// Stored file name, e.g. "app.v2.js".
        let name: String
        /// What the page asks for; also the key of the revalidation request.
        let path: String
    }

    /// Mirrored set, in the order the page asks for it. Kept in step with
    /// `ASSETS` in scripts/gen-site-assets.js: the generator's `--check` fails if
    /// the manifest and the files on disk disagree, and the tests fail if this
    /// list and the JavaScript `PATHS` table disagree.
    static let supported: [Asset] = [
        Asset(name: "app.v2.js", path: "/asset/app.v2.js"),
        Asset(name: "app.v2.css", path: "/asset/app.v2.css"),
        Asset(name: "app.v2.bookdisplay.js", path: "/asset/app.v2.bookdisplay.js"),
        Asset(name: "app.v2.config.js", path: "/asset/app.v2.config.js"),
        Asset(name: "app.v2.read.js", path: "/asset/app.v2.read.js"),
        Asset(name: "app.v2.chapterdisplay.js", path: "/asset/app.v2.chapterdisplay.js"),
        Asset(name: "stv.tts.js", path: "/stv.tts.js"),
        Asset(name: "hanviet.js", path: "/hanviet.js")
    ]

    static let folderName = "site-assets"

    /// Must stay identical to `SangTacHttpPlugin.defaultUserAgent`: the mirror
    /// asks the same servers for the same files, and a different client is a
    /// different answer from the site's edge.
    static let userAgent = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) "
        + "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"

    // MARK: - Locations

    /// Locates the SwiftPM resource bundle without SwiftPM's fatalError-on-miss
    /// accessor. Falls back to a flat lookup in the app bundle in case a future
    /// Xcode flattens the folder instead of copying it as a `.bundle`.
    static let resourceBundle: Bundle? = {
        if let resourceURL = Bundle.main.resourceURL,
           let entries = try? FileManager.default.contentsOfDirectory(
               at: resourceURL, includingPropertiesForKeys: nil) {
            for entry in entries
            where entry.pathExtension == "bundle"
                && entry.lastPathComponent.contains("SangTacAppPlugin") {
                if let bundle = Bundle(url: entry) { return bundle }
            }
        }
        return Bundle.main
    }()

    static let bundleDirectory: URL? = {
        guard let bundle = resourceBundle else { return nil }
        if let url = bundle.url(forResource: folderName, withExtension: nil) { return url }
        return bundle.resourceURL?.appendingPathComponent(folderName, isDirectory: true)
    }()

    /// Application Support, not Caches: iOS may evict Caches under storage
    /// pressure, and an evicted mirror is a silent return to slow boots.
    static let cacheDirectory: URL? = {
        guard let base = FileManager.default.urls(
            for: .applicationSupportDirectory, in: .userDomainMask).first else { return nil }
        let dir = base.appendingPathComponent("stv-site-assets", isDirectory: true)
        do {
            try FileManager.default.createDirectory(
                at: dir, withIntermediateDirectories: true)
        } catch {
            return nil
        }
        return dir
    }()

    // MARK: - Reading

    private static let stamps: [String: String] = {
        guard let directory = bundleDirectory else { return [:] }
        let manifest = directory.appendingPathComponent("manifest.json")
        guard let data = try? Data(contentsOf: manifest),
              let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let files = root["files"] as? [[String: Any]] else { return [:] }
        var out: [String: String] = [:]
        for file in files {
            guard let name = file["name"] as? String else { continue }
            out[name] = (file["lastModified"] as? String) ?? ""
        }
        return out
    }()

    /// The text of one mirrored asset plus the Last-Modified it was published
    /// with, preferring the refreshed copy over the shipped snapshot.
    static func read(_ asset: Asset) -> (text: String, stamp: String)? {
        if let directory = cacheDirectory {
            let file = directory.appendingPathComponent(asset.name)
            if let text = try? String(contentsOf: file, encoding: .utf8), !text.isEmpty {
                let stampFile = directory.appendingPathComponent(asset.name + ".stamp")
                let stamp = (try? String(contentsOf: stampFile, encoding: .utf8)) ?? ""
                return (text, stamp.trimmingCharacters(in: .whitespacesAndNewlines))
            }
        }
        guard let directory = bundleDirectory else { return nil }
        let file = directory.appendingPathComponent(asset.name)
        guard let text = try? String(contentsOf: file, encoding: .utf8), !text.isEmpty else {
            return nil
        }
        return (text, stamps[asset.name] ?? "")
    }

    /// Names that are being served from the refreshed copy rather than the
    /// snapshot. Reported once per launch so the device log says which copy is
    /// actually in play.
    static func refreshedNames() -> [String] {
        guard let directory = cacheDirectory else { return [] }
        return supported.map { $0.name }.filter { name in
            let file = directory.appendingPathComponent(name)
            guard let attributes = try? FileManager.default.attributesOfItem(atPath: file.path),
                  let size = attributes[.size] as? Int else { return false }
            return size > 0
        }
    }

    /// The document-start script that hands the whole table to the page. Returns
    /// nil when nothing is bundled, which leaves `assetMirror` inert.
    static func script() -> String? {
        var table: [String: String] = [:]
        var stampTable: [String: String] = [:]
        for asset in supported {
            guard let entry = read(asset) else { continue }
            table[asset.name] = entry.text
            stampTable[asset.name] = entry.stamp
        }
        guard !table.isEmpty,
              let tableData = try? JSONSerialization.data(withJSONObject: table),
              let stampData = try? JSONSerialization.data(withJSONObject: stampTable),
              let tableJSON = String(data: tableData, encoding: .utf8),
              let stampJSON = String(data: stampData, encoding: .utf8) else { return nil }
        return "window.__stvSiteAssets = " + tableJSON + ";"
            + "window.__stvSiteStamps = " + stampJSON + ";"
    }

    static func tableNames() -> [String] {
        supported.compactMap { read($0) == nil ? nil : $0.name }
    }

    // MARK: - Writing

    /**
     Persists one revalidated asset. Everything about this is defensive: the name
     has to be one we mirror, the body has to look like the kind of file it claims
     to be, and a body that fails either test is dropped rather than stored. A
     truncated download written over a good snapshot is exactly how a mirror turns
     into a permanently broken app.
     */
    @discardableResult
    static func store(name: String, text: String, stamp: String) -> Bool {
        guard let asset = supported.first(where: { $0.name == name }) else { return false }
        guard plausible(asset: asset, text: text) else { return false }
        guard let directory = cacheDirectory else { return false }
        do {
            try text.write(to: directory.appendingPathComponent(name),
                           atomically: true, encoding: .utf8)
            try stamp.write(to: directory.appendingPathComponent(name + ".stamp"),
                            atomically: true, encoding: .utf8)
            return true
        } catch {
            return false
        }
    }

    /// Drops a refreshed copy so the shipped snapshot takes over again.
    static func forget(name: String) {
        guard let directory = cacheDirectory else { return }
        try? FileManager.default.removeItem(at: directory.appendingPathComponent(name))
        try? FileManager.default.removeItem(
            at: directory.appendingPathComponent(name + ".stamp"))
    }

    static func forgetAll() {
        for asset in supported { forget(name: asset.name) }
    }

    /// The cheapest possible sanity test for a downloaded asset. It only has to
    /// catch the failures that actually happen: an error page saved under a
    /// script name, and a response cut short mid-file.
    static func plausible(asset: Asset, text: String) -> Bool {
        guard text.utf8.count > 512 else { return false }
        let head = String(text.prefix(200)).trimmingCharacters(in: .whitespacesAndNewlines)
        if head.hasPrefix("<") { return false }
        if asset.name.hasSuffix(".js") {
            // The site's bundles are IIFEs or plain declarations; a file that
            // never closes a brace is a truncated download.
            guard text.contains("{") && text.contains("}") else { return false }
        }
        if asset.name.hasSuffix(".css") {
            guard text.contains("{") && text.contains("}") else { return false }
        }
        return true
    }
}

/**
 One conditional GET, run to completion on a background queue.

 `URLSession.dataTask` plus a semaphore rather than `async`/`await`: this is
 called from a `CAPPluginCall` handler that already has its own background queue,
 and the whole refresh is at most eight requests of which almost all answer 304.
 */
enum SiteAssetFetcher {

    private final class Box {
        var data: Data?
        var response: URLResponse?
    }

    static func get(_ request: URLRequest, timeout: TimeInterval = 25) -> (Data, URLResponse)? {
        let semaphore = DispatchSemaphore(value: 0)
        let box = Box()
        let task = URLSession.shared.dataTask(with: request) { data, response, _ in
            box.data = data
            box.response = response
            semaphore.signal()
        }
        task.resume()
        if semaphore.wait(timeout: .now() + timeout) == .timedOut {
            task.cancel()
            return nil
        }
        guard let data = box.data, let response = box.response else { return nil }
        return (data, response)
    }
}
